### DISCUSSION TITLE
markdown

### DISCUSSION THREAD

**Discussion by giscus** [Yiov/vitepress-doc#10] [General]
# markdown

我的vitpress文档教程

https://vitepress.yiov.top/markdown.html

**Comment by mnjun9527** [comment]
写的真叫好，markdown 可惜没有找到   markdown  内自定义CSS样式，不知道是否支持

**Reply by Yiov** [reply]
Vitepress官方文档中内置了CSS预处理器，安装使用即可

https://vitepress.dev/zh/guide/using-vue#using-css-pre-processors

也可以单独编写css文件后引入md

**Reply by mnjun9527** [reply]
非常感谢博主的回复，我想在markdown  的顶部添加苹果的3个小圆点，让代码块看起来更加的美观
``` CSS
/* 代码块主题 */
/* 顶部 */
.md-fences {
    color: #c5c8c6;
    background-color: #21252b;
    border-radius: 5px;
    box-shadow: 0 10px 30px 0 rgb(0 0 0 / 40%);
    padding-top: 30px;
    font-family: monospace, 'PingFang SC', 'Microsoft YaHei';
}
 
.md-fences::before {
    background: #fc625d;
    border-radius: 50%;
    box-shadow: 20px 0 #fdbc40, 40px 0 #35cd4b;
    content: ' ';
    height: 12px;
    left: 12px;
    margin-top: -20px;
    position: absolute;
    width: 12px;
}
```

CSS有了，就不知道该如何添加，我去研究一下，但是不知道自己能否搞定，如果博主愿意的话，能不能把这篇自定义页更新一下，万分感谢！

**Reply by mnjun9527** [reply]
说错了，是在Markdown,代码款的顶部加上 三个小圆点

**Reply by mnjun9527** [reply]
代码块

**Reply by Yiov** [reply]
更改成对应的 `class` 就行了

新建一个 `vp-code-group.css` 文件

```
/* .vitepress\theme\style\vp-code-group.css */

/* 代码块tab */
.vp-code-group .tabs {
    padding-top: 30px;
}

/* 代码块tab-顶部小圆点 */
.vp-code-group .tabs::before {
    background: #fc625d;
    border-radius: 50%;
    box-shadow: 20px 0 #fdbc40, 40px 0 #35cd4b;
    content: ' ';
    height: 12px;
    width: 12px;
    left: 12px;
    margin-top: -20px;
    position: absolute;
}


/* 代码组 */
.vp-code-group {
    color: var(--vp-c-black-soft);
    border-radius: 8px;
    box-shadow: 0 10px 30px 0 rgb(0 0 0 / 40%);
}
```

最后在 `index.css` 中引入生效

```
/* .vitepress\theme\style\index.css */
@import './vp-code-group.css';
```

具体操作方式看教程：https://vitepress.yiov.top/style.html#%E4%BB%A3%E7%A0%81%E7%BB%84%E9%A3%8E%E6%A0%BC

**Reply by mnjun9527** [reply]
非常的感谢你，我访问你的网站时，网站打不开了， 我登录GITHUB 发现您的回复   十分感谢您

**Reply by mnjun9527** [reply]
在您的指点下，摸索到了 这个自定义的方法。 通过F12看CSS 进行改写，十分感谢您的指点。

**Comment by mnjun9527** [comment]
我发现一个问题，如果在左下角点了退出登录，退出gothub  退出成功以后，你就再也看不到评论区了。

一直显示加载失败。 然后也没有登录的按钮和办法。  后来实在登录不上，我用服务器的windows登录才进来的。     请谨慎测试，最好用小号

**Reply by Yiov** [reply]
giscus有时候会bug，但是也不多，稳定性和外观上都是很棒的，加载不了挂个梯子有时候就可以了

**Comment by Aurorxa** [comment]
对于 GitHub 风格的容器，会显示英文，如：NOTE、IMPORTANT 等，虽然我认为还行，但是可能很多人有强迫症就是喜欢中文，那么就可以这么做，在 config.mts 中的 markdown 配置项，将 NOTE 等替换为中文，代码如下：

```ts
  markdown: { // markdown 配置
    math: true,
    lineNumbers: true, // 行号显示
    image: {
      // 开启图片懒加载
      lazyLoading: true
    },
    // 组件插入h1标题下
    config: (md) => {
      // 创建 markdown-it 插件
      md.use((md) => {
        const defaultRender = md.render
        md.render = function (...args) {
          const [content, env] = args
          const isHomePage = env.path === '/' || env.relativePath === 'index.md'  // 判断是否是首页

          if (isHomePage) {
            return defaultRender.apply(md, args) // 如果是首页，直接渲染内容
          }
          // 调用原始渲染
          let defaultContent = defaultRender.apply(md, args)
          // 替换内容
          defaultContent = defaultContent.replace(/NOTE/g, '提醒')
                .replace(/TIP/g, '建议')
                .replace(/IMPORTANT/g, '重要')
                .replace(/WARNING/g, '警告')
                replace(/CAUTION/g, '注意')
          // 返回渲染的内容
          return defaultContent
        }
      })
    }
  },
```

**Reply by Yiov** [reply]
佬的动手能力真的强，不过GitHub的警报在使用上和容器一致

`> [!NOTE] 加上自定义标题即可`

**Reply by Aurorxa** [reply]
本地的 Typora 不支持，仁者见仁吧，看习惯！！！

**Reply by Yiov** [reply]
原来是这样，还没有接触过 Typora ，那我会将您的代码加入文档中，以便有同样需求的人使用

再次感谢您对文档完善提供的建议

**Reply by Aurorxa** [reply]
对于 Github 风格警报，我这边做了优化，形成跑马灯的效果（边框线条动画），如下所示：

```css

@keyframes clippath {
    0%,
    100% {
        clip-path: inset(0 0 90% 0);
    }
    25% {
        clip-path: inset(0 90% 0 0);
    }
    50% {
        clip-path: inset(90% 0 0 0);
    }
    75% {
        clip-path: inset(0 0 0 90%);
    }
}


/* NOTE容器:背景色、左侧 */
.custom-block.note {
  background-color: var(--vp-custom-block-note-bg);
  border-left: 5px solid var(--vp-custom-block-note);
  box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3);
  /* 实现跑马灯的效果 */
  position: relative;
  transition: all .3s;
}

.custom-block.note:hover{
  filter: contrast(1.1);
}

.custom-block.note:active{
  filter: contrast(0.9);
}

/* 实现跑马灯的效果 */
.custom-block.note.github-alert::before,
.custom-block.note.github-alert::after {
    content: "";
    position: absolute;
    top: -2px;
    left: -5px;
    right: -2px;
    bottom: -2px;
    border: 2px solid var(--vp-custom-block-note);
    transition: all .5s;
    animation: clippath 6s infinite linear;
    border-radius: 10px;
}
/* 实现跑马灯的效果 */
.custom-block.note.github-alert::after {
    animation: clippath 6s infinite -3s linear;
}


/* NOTE容器:svg图 */
.custom-block.note [class*="custom-block-title"]::before {
  content: '';
  background-image: url("data:image/svg+xml;utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath d='M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm-1-11v6h2v-6h-2zm0-4v2h2V7h-2z' fill='%234cb3d4'/%3E%3C/svg%3E");
  width: 21px;
  height: 21px;
  display: inline-block;
  vertical-align: middle;
  position: relative;
  margin-right: 4px;
  line-height: 1;
  top: 0;
}

.custom-block.note [class*="custom-block-title"] {
  display: inline-flex; /* 使用flex布局以确保对齐 */
  align-items: center; /* 垂直居中对齐图标和文字 */
  vertical-align: middle;
}


```
