### DISCUSSION TITLE
style

### DISCUSSION THREAD

**Discussion by giscus** [Yiov/vitepress-doc#11] [General]
# style

我的vitpress文档教程

https://vitepress.yiov.top/style.html

**Comment by mnjun9527** [comment]
博主有在哪里开课吗   比如B站或者抖音啥的   或者粉丝交流群有吗

**Reply by Yiov** [reply]
我也只是个Vitepress的爱好者，非科班出生，工作忙没时间开群交流。有疑问提 [issues](https://github.com/Yiov/vitepress-doc/issues )，当然如果我不会就没办法了

**Reply by mnjun9527** [reply]
您好，网站打不开了

**Reply by Yiov** [reply]
玩github必须得学会翻墙

不是网站打不开，GitHub就是半墙状态，时而可以时而不行，翻墙了就随便开

**Reply by mnjun9527** [reply]
加速器可梯子都有喔，不然我怎么进GIEHUB
真进不去了

**Reply by mnjun9527** [reply]
https://vitepress.yiov.top/nav/  您真的可以访问吗？

**Reply by mnjun9527** [reply]
好吧，我的站我可以访问， 之前收藏您的网站  的页面已经全部不能访问了，  可能是网络波动，  晚点我再试试。谢谢

**Comment by mnjun9527** [comment]
您好，我在GIEHUB 看到一款主题十分漂亮，奈何研究了好几天，都没有能套入自己的项目， 不知道您是否有空可以看看， 特此留下地址，希望没有打扰到您https://github.com/lauset/vitepress-theme-vuetom

**Reply by Yiov** [reply]
无论是完全照搬，还是微调，都是十分建议按照他的文档拉取、安装依赖、启动，这样能更好的查看效果，以及快速找到自己想要的东西，只有多研究才能印象深刻得新应手

**Reply by mnjun9527** [reply]
感谢，这几天我也拉取项目安装依赖，确实运行了他的项目， 拉取过来的项目里面有好多的文档， 但是他好像无法应用到已有的项目内。  或是我不知道如何引用这些主题，

这方面的资料确实太少了。  今天我通过观察他的页面，来修改我的CSS， 得到了他的标题样式。 

 他的自定义语法，我暂时还无法获取，我也尝试翻了下源码，层级太复杂了，无奈看不懂。搜寻了很多地方发现这方面的资料真是少之又少。  看来只能暂时这样了，非常感谢您的指点

**Comment by mnjun9527** [comment]
![WQ$DTRC A61@4U3M$2Y2089](https://github.com/Yiov/vitepress-doc/assets/165643276/38024843-27fc-4851-9c7b-5ff76bef3cef)
![%QMQZ` JO7F51F4NTT63AVU](https://github.com/Yiov/vitepress-doc/assets/165643276/d5ac0cea-df39-449d-ba28-0b6516e2c08f)
![TZVYTS4458 ~E)_{64YG![WQ$DTRC A61@4U3M$2Y2089](https://github.com/Yiov/vitepress-doc/assets/165643276/38024843-27fc-4851-9c7b-5ff76bef3cef)
![%QMQZ` JO7F51F4NTT63AVU](https://github.com/Yiov/vitepress-doc/assets/165643276/d5ac0cea-df39-449d-ba28-0b6516e2c08f)
8](https://github.com/Yiov/vitepress-doc/assets/165643276/0448fa74-a13d-4400-b0bb-d37e46974a69)
![3%UEV~K0(DEO3W}HBFTDD%R](https://github.com/Yiov/vitepress-doc/assets/165643276/44be2819-d0d0-42d1-a41a-22e6e3d14f7c)

附上部分贴补

**Comment by get1024** [comment]
查尔斯的页面做的太顶了。好多个人实现的美化，奈何我并不想fork……………

**Reply by Yiov** [reply]
查尔斯的页面是真的不错，有点东西的。对我个人而言不是太喜欢美化，每个人喜好不同嘛，我就简单写写东西完事

**Reply by get1024** [reply]
老哥，请教一下，评论插件配置完毕后，我遇到了以下问题。
在about me文件夹下有目录结构如下
> about me
  - index.md
  - demo1.md
  - demo2.md
我在index.md下评论，有时候会在index.md和demo1.md或者demo2.md中任意一个同样显示index.md的评论。说任意的原因是：我也不清楚它的原因是什么。
我查阅repo的讨论之后，发现之前在index.md评论的内容，在讨论里显示的路径却是about_me\demo[1`or`2].md。但这似乎解释了为什么在index评论的内容会在demo[1`or`2]显示的原因，但是又让我更困惑了……就是：为什么路径不是`about_me\`，index的评论区却仍然有评论……

您之前有这种情况吗？

**Reply by Yiov** [reply]
没有这种情况哦，giscus在每个页面下的数据是独立的

* about/index.md

* about/demo1.md

* about/demo2.md

是三个独立的页面，没有评论乱串的现象


我去你主页看了一下，都是正常啊，仓库也没问题

sponsor 和 friendChains 都是不同时间留的不同言论，repo每条讨论上方都会有一条链接，告诉你讨论在那个页面（路径），下面就是评论的数据

**Comment by AlianBlank** [comment]
请问一下.如何才能把左侧的导航栏和现在浏览的页面高亮显示并定位到当前的位置呢?我找了一圈也没有找到这个部分的设置.

**Reply by Yiov** [reply]
没有理解到你的意思，可以截图或者用 [StackBlitz](https://vitepress.new/) 做一个小小的demo，我看一下

**Reply by Yiov** [reply]
看了一下你的项目，侧边栏分组有个 `base` ，是从vuepress转过来的吧，而vitepress官方并没有使用此参数

需要你填写文章完整的路径，文章多的话，也可以用自动侧边栏插件



```diff
sidebar: [
      {
        text: 'Unity客户端',
-       // base: '/unity/',
        collapsed: false,
        items: [
+          { text: '准备工作', link: '/unity/ready' },
          {
            text: '组件',
-            // base: '/unity/component/',
            collapsed: false,
+            items: [{ text: '事件', link: '/unity/component/event' }],
          },
        ],
      },
    ],
```

这样路由就没问题了，我表述不理解的话，可以看我做的小 [👉DEMO](https://stackblitz.com/edit/vite-euzmto)

**Reply by AlianBlank** [reply]
我理解了你的意思.我不是侧边栏多的问题.而是我希望.比如我现在是在看事件.那么左侧的事件这个栏应该是高亮的.表示我现在正在浏览的页面.

**Reply by AlianBlank** [reply]
我今天在你的站点使用了自动侧边栏.发现他的排序规则并没有我想要的效果.虽然的确实现了自动生成侧边栏的效果.我也配置了诸多参数.使用文件前缀排序.H1 标题排序.但是地址和标题本身就会发生变化.这不是我想要的.诸如按照formater 的时间.排序.这样对于我的维护成本较高.这样我还是手动控制列表更加适合

**Reply by Yiov** [reply]
就是因为配置问题呀，所以我写了参考样式

关于侧边栏，我只是看你配置不对，是没有看认真看文档，仍记着Vuepress的配置方式，担心你记错才提了一嘴，这个咱们暂且打住。

请先尝试我上面给的方案，如果不对请截图表述吧

![](https://github.com/user-attachments/assets/ad35e173-ae25-4f9e-bc43-ad8a49f2837c)

**Reply by AlianBlank** [reply]
非常感谢.我已经将base 去掉.并且得到了我想要的效果.
但是现在如果是在白天的模式下.显示的颜色太不明显了.有什么更好的解决方式吗?
比如白天是一种颜色.黑色是一种颜色

**Reply by Yiov** [reply]
看下我的 [样式美化](https://vitepress.yiov.top/style.html) 教程，修改全局css样式颜色

**Reply by AlianBlank** [reply]
https://gameframex.doc.alianblank.com/  我配置了H1 标题的颜色.但是在发布之后就没有了
![Uploading image.png…]()

**Reply by AlianBlank** [reply]
![image](https://github.com/user-attachments/assets/08ae61b8-b1ad-4050-8ef5-e96300bb8e83)

**Reply by AlianBlank** [reply]
以下为开发环境的截图
![image](https://github.com/user-attachments/assets/a19e7b24-55ec-42eb-8b72-228f4a6eb367)

**Reply by Yiov** [reply]
本地没有问题，一般就没啥问题，除非你推送部署失败

**Comment by chay73** [comment]
求如何新增在页面顶部显示文档字数和阅读时间的教程～

**Reply by Yiov** [reply]
如果这些都加上，就是blog形式的了

暂时不会有计划编写，不过你可以看 [Nolebase大佬](https://nolebase-integrations.ayaka.io/pages/zh-CN/integrations/vitepress-plugin-page-properties/) 的教程

**Reply by Yiov** [reply]
已更新教程，[请查看食用](https://vitepress.yiov.top/components.html#%E5%AD%97%E6%95%B0%E5%8F%8A%E9%98%85%E8%AF%BB%E6%97%B6%E9%97%B4)

**Reply by chay73** [reply]
感谢～～～～

**Comment by Aurorxa** [comment]
出现了两次更新时间

**Reply by Yiov** [reply]
感谢，大意忘记删掉了

**Comment by Aurorxa** [comment]
对于代码组，我进行了修改，不会会导致只有代码组才会显示 mac 图标，而普通的代码区不会显示 mac 图标，我的想法是，所有关于代码的都要显示 mac 图标，我的代码如下：

```css
/* .vitepress/theme/style/vp-code.css */

/* 为代码块添加 macOS 风格的小圆点 */
div[class*="language-"].vp-adaptive-theme.line-numbers-mode {
  position: relative;
  border-radius: 8px;
  overflow: hidden;
  background-color: #f5f5f5; /* 背景色，可根据需要调整 */
  box-shadow: 0 10px 30px 0 rgb(0 0 0 / 40%); /* 可选的阴影效果 */ 
  padding-top: 24px; /* 给小圆点留出空间 */
}

/* 添加小圆点 */
div[class*="language-"].vp-adaptive-theme.line-numbers-mode:not(.vp-code-group .line-numbers-mode)::before {
  content: "";
  display: block;
  position: absolute;
  top: 12px;
  left: 12px;
  width: 12px;
  height: 12px;
  background-color: #ff5f56; /* 红色 */
  border-radius: 50%;
  box-shadow: 20px 0 0 #ffbd2e, 40px 0 0 #27c93f; /* 黄色和绿色的小圆点 */
  z-index: 1; /* 确保圆点在代码块上方 */
}

/* 调整行号的样式 */
.vp-doc .line-numbers-wrapper {
  top: 0; /* 调整行号位置，使其与代码内容对齐 */
  right: 0; /* 确保行号容器靠右对齐 */
  height: 100%; /* 使行号容器填满可用空间 */
  position: absolute; /* 确保绝对定位 */
  padding-top: 44px; /* 移除多余填充 */
  border-right: none;
}

/* 使用伪元素调整右边框位置 */
.vp-doc .line-numbers-wrapper::after {
  content: "";
  position: absolute;
  top: 44px; /* 将右边框下移24像素 */
  right: 0; /* 将右边框置于容器右侧 */
  height: calc(100% - 66px); /* 设置边框高度，减去顶部偏移 */
  border-right: 1px solid var(--vp-code-block-divider-color);
}



```

```css
/* .vitepress/theme/style/vp-code-group.css */

/* 代码块tab */
.vp-code-group .tabs {
  padding-top: 30px;
}

/* 代码块tab-顶部小圆点 */
.vp-code-group .tabs::before {
  background: #fc625d;
  border-radius: 50%;
  box-shadow: 20px 0 #fdbc40, 40px 0 #35cd4b;
  content: ' ';
  height: 12px;
  width: 12px;
  left: 12px;
  margin-top: -15px;
  position: absolute;
}

/* 代码组的容器样式 */
.vp-code-group {
  color: var(--vp-c-black-soft);
  border-radius: 8px;
  box-shadow: 0 10px 30px 0 rgb(0 0 0 / 40%);
}

/* 在代码组内部的代码块样式 */
.vp-code-group div[class*="language-"].vp-adaptive-theme.line-numbers-mode {
  padding-top: 24px; /* 确保代码块内的间距正确 */
  border-radius: 8px; /* 与外部容器的边角一致 */
  box-shadow: none; /* 避免嵌套的阴影叠加 */
  position: relative;
}

/* 确保 group 内的代码块不重复显示小圆点 */
.vp-code-group div[class*="language-"].vp-adaptive-theme.line-numbers-mode::before {
  display: none;
}
```

在 index.css 中引入这几个 css 文件就可以了，内容如下：

```css
@import './vp-code-group.css';
@import './vp-code.css';
@import './blockquote.css';
@import './var.css';
```
