### ISSUE TITLE
可以创建一个标题栏毛玻璃的教程吗

### ISSUE THREAD

**Issue by ikenxuan** [Yiov/vitepress-doc#14]
如题，想要这种效果，朦胧感第一眼看上去就非常高级
![9c9dd104324590eb03b6edc49d127c6c](https://github.com/user-attachments/assets/2038dbb8-e5d4-4ec2-80f0-0208ef2118a5)

顺便感谢大佬的教程帮我美化了我自己的文档，这是我的文档 https://github.com/ikenxuan/kkkkkk-10086/tree/docs。
之前是可以实现毛玻璃的，但是只有在 https://github.com/ikenxuan/kkkkkk-10086/commit/e3c4c758215b2ae999ced03a0cb84f4170577e2f 的提交中的dev模式下才能实现，编译后预览毛玻璃效果就不见了
- 这里是原有的代码实现
  - https://github.com/ikenxuan/kkkkkk-10086/blob/6265173103f9ad0bf411e3fc4755ab2969c9d98b/.vitepress/theme/style/var.css#L14

为什么说只有 https://github.com/ikenxuan/kkkkkk-10086/commit/e3c4c758215b2ae999ced03a0cb84f4170577e2f 版本的才能实现，我后面不知道装了什么，现在dev模式下也没法实现了，也排查不出来。
还望大佬指导

**Comment by Yiov** [comment]
你这个只有 `.VPNavBar:not(.home.top) .content-body` 属性是有效的

其他属性在vitepress主题文件中 `VPNavBar.vue` 可以找到

如你所愿，我将代码写在教程中了，你可以看一下 [导航栏毛玻璃效果](https://vitepress.yiov.top/style.html#%E5%AF%BC%E8%88%AA%E6%A0%8F%E6%AF%9B%E7%8E%BB%E7%92%83)

**Comment by ikenxuan** [comment]
> 你这个只有 `.VPNavBar:not(.home.top) .content-body` 属性是有效的
> 
> 其他属性在vitepress主题文件中 `VPNavBar.vue` 可以找到
> 
> 如你所愿，我将代码写在教程中了，你可以看一下 [导航栏毛玻璃效果](https://vitepress.yiov.top/style.html#%E5%AF%BC%E8%88%AA%E6%A0%8F%E6%AF%9B%E7%8E%BB%E7%92%83)

好的，谢谢大佬解答和奉献，我也cv下你的代码学习了

**Comment by ikenxuan** [comment]
大佬，当前页大纲这里好像有点奇怪
![image](https://github.com/user-attachments/assets/cf373fce-958e-4f06-b8ff-633008cacaca)
移动端的话，头顶如果能一样毛玻璃就更好了
![image](https://github.com/user-attachments/assets/c31bd331-cf09-4f52-a655-20325ec86d11)
移动端我使用了以下代码来实现
```css
@media (max-width: 960px) {
    .VPLocalNav {
      position: sticky;
      top: 0;
      left: 0;
      z-index: var(--vp-z-index-local-nav);
      border-bottom: 1px solid var(--vp-c-gutter);
      padding-top: var(--vp-layout-top-height, 0px);
      width: 100%;
      background-color: rgba(255, 255, 255, 0);
      backdrop-filter: blur(10px);
    }
  }
```
![image](https://github.com/user-attachments/assets/29d763b3-87be-4838-b5a6-2fa110c8bdc6)

但是同样的，分隔线我没有找到它的样式在哪，所以没法移除这个分割线
